-- H2 データベースでは user という名前のテーブルが作成できないため
-- ダブルクォーテーションで囲って "user" とする 
CREATE TABLE IF NOT EXISTS "user" (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(254) UNIQUE,
	password VARCHAR(256) NOT NULL,
	role VARCHAR(50) DEFAULT 'ROLE_GENERAL'
);

CREATE TABLE IF NOT EXISTS category (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	category_id INT NOT NULL,
	slug VARCHAR(50) UNIQUE,
	title VARCHAR(50) NOT NULL,
	thumbnail VARCHAR(256),
	body TEXT NOT NULL,
	posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES "user"(id),
	FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS comment (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	post_id INT NOT NULL,
	body TEXT NOT NULL,
	posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES "user"(id),
	FOREIGN KEY (post_id) REFERENCES post(id)
);